// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.backpocket.data;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeopleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:main.People)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    java.util.List<com.backpocket.data.Data.Person> 
        getMembersList();
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    com.backpocket.data.Data.Person getMembers(int index);
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    java.util.List<? extends com.backpocket.data.Data.PersonOrBuilder> 
        getMembersOrBuilderList();
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    com.backpocket.data.Data.PersonOrBuilder getMembersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code main.People}
   */
  public  static final class People extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:main.People)
      PeopleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use People.newBuilder() to construct.
    private People(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private People() {
      members_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private People(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                members_ = new java.util.ArrayList<com.backpocket.data.Data.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              members_.add(
                  input.readMessage(com.backpocket.data.Data.Person.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          members_ = java.util.Collections.unmodifiableList(members_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.backpocket.data.Data.internal_static_main_People_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.backpocket.data.Data.internal_static_main_People_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.backpocket.data.Data.People.class, com.backpocket.data.Data.People.Builder.class);
    }

    public static final int MEMBERS_FIELD_NUMBER = 1;
    private java.util.List<com.backpocket.data.Data.Person> members_;
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    public java.util.List<com.backpocket.data.Data.Person> getMembersList() {
      return members_;
    }
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    public java.util.List<? extends com.backpocket.data.Data.PersonOrBuilder> 
        getMembersOrBuilderList() {
      return members_;
    }
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    public com.backpocket.data.Data.Person getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated .main.Person Members = 1;</code>
     */
    public com.backpocket.data.Data.PersonOrBuilder getMembersOrBuilder(
        int index) {
      return members_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < members_.size(); i++) {
        output.writeMessage(1, members_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < members_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, members_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.backpocket.data.Data.People)) {
        return super.equals(obj);
      }
      com.backpocket.data.Data.People other = (com.backpocket.data.Data.People) obj;

      boolean result = true;
      result = result && getMembersList()
          .equals(other.getMembersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.backpocket.data.Data.People parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.backpocket.data.Data.People parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.backpocket.data.Data.People parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.backpocket.data.Data.People parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.backpocket.data.Data.People parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.backpocket.data.Data.People parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.backpocket.data.Data.People parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.backpocket.data.Data.People parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.backpocket.data.Data.People parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.backpocket.data.Data.People parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.backpocket.data.Data.People parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.backpocket.data.Data.People parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.backpocket.data.Data.People prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code main.People}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:main.People)
        com.backpocket.data.Data.PeopleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.backpocket.data.Data.internal_static_main_People_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.backpocket.data.Data.internal_static_main_People_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.backpocket.data.Data.People.class, com.backpocket.data.Data.People.Builder.class);
      }

      // Construct using com.backpocket.data.Data.People.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMembersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          membersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.backpocket.data.Data.internal_static_main_People_descriptor;
      }

      @java.lang.Override
      public com.backpocket.data.Data.People getDefaultInstanceForType() {
        return com.backpocket.data.Data.People.getDefaultInstance();
      }

      @java.lang.Override
      public com.backpocket.data.Data.People build() {
        com.backpocket.data.Data.People result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.backpocket.data.Data.People buildPartial() {
        com.backpocket.data.Data.People result = new com.backpocket.data.Data.People(this);
        int from_bitField0_ = bitField0_;
        if (membersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            members_ = java.util.Collections.unmodifiableList(members_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.members_ = members_;
        } else {
          result.members_ = membersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.backpocket.data.Data.People) {
          return mergeFrom((com.backpocket.data.Data.People)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.backpocket.data.Data.People other) {
        if (other == com.backpocket.data.Data.People.getDefaultInstance()) return this;
        if (membersBuilder_ == null) {
          if (!other.members_.isEmpty()) {
            if (members_.isEmpty()) {
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMembersIsMutable();
              members_.addAll(other.members_);
            }
            onChanged();
          }
        } else {
          if (!other.members_.isEmpty()) {
            if (membersBuilder_.isEmpty()) {
              membersBuilder_.dispose();
              membersBuilder_ = null;
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000001);
              membersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMembersFieldBuilder() : null;
            } else {
              membersBuilder_.addAllMessages(other.members_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.backpocket.data.Data.People parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.backpocket.data.Data.People) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.backpocket.data.Data.Person> members_ =
        java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          members_ = new java.util.ArrayList<com.backpocket.data.Data.Person>(members_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.backpocket.data.Data.Person, com.backpocket.data.Data.Person.Builder, com.backpocket.data.Data.PersonOrBuilder> membersBuilder_;

      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public java.util.List<com.backpocket.data.Data.Person> getMembersList() {
        if (membersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(members_);
        } else {
          return membersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public int getMembersCount() {
        if (membersBuilder_ == null) {
          return members_.size();
        } else {
          return membersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public com.backpocket.data.Data.Person getMembers(int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);
        } else {
          return membersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder setMembers(
          int index, com.backpocket.data.Data.Person value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.set(index, value);
          onChanged();
        } else {
          membersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder setMembers(
          int index, com.backpocket.data.Data.Person.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.set(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder addMembers(com.backpocket.data.Data.Person value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(value);
          onChanged();
        } else {
          membersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder addMembers(
          int index, com.backpocket.data.Data.Person value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(index, value);
          onChanged();
        } else {
          membersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder addMembers(
          com.backpocket.data.Data.Person.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder addMembers(
          int index, com.backpocket.data.Data.Person.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder addAllMembers(
          java.lang.Iterable<? extends com.backpocket.data.Data.Person> values) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, members_);
          onChanged();
        } else {
          membersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder clearMembers() {
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          membersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public Builder removeMembers(int index) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.remove(index);
          onChanged();
        } else {
          membersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public com.backpocket.data.Data.Person.Builder getMembersBuilder(
          int index) {
        return getMembersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public com.backpocket.data.Data.PersonOrBuilder getMembersOrBuilder(
          int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);  } else {
          return membersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public java.util.List<? extends com.backpocket.data.Data.PersonOrBuilder> 
           getMembersOrBuilderList() {
        if (membersBuilder_ != null) {
          return membersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(members_);
        }
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public com.backpocket.data.Data.Person.Builder addMembersBuilder() {
        return getMembersFieldBuilder().addBuilder(
            com.backpocket.data.Data.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public com.backpocket.data.Data.Person.Builder addMembersBuilder(
          int index) {
        return getMembersFieldBuilder().addBuilder(
            index, com.backpocket.data.Data.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .main.Person Members = 1;</code>
       */
      public java.util.List<com.backpocket.data.Data.Person.Builder> 
           getMembersBuilderList() {
        return getMembersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.backpocket.data.Data.Person, com.backpocket.data.Data.Person.Builder, com.backpocket.data.Data.PersonOrBuilder> 
          getMembersFieldBuilder() {
        if (membersBuilder_ == null) {
          membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.backpocket.data.Data.Person, com.backpocket.data.Data.Person.Builder, com.backpocket.data.Data.PersonOrBuilder>(
                  members_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          members_ = null;
        }
        return membersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:main.People)
    }

    // @@protoc_insertion_point(class_scope:main.People)
    private static final com.backpocket.data.Data.People DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.backpocket.data.Data.People();
    }

    public static com.backpocket.data.Data.People getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<People>
        PARSER = new com.google.protobuf.AbstractParser<People>() {
      @java.lang.Override
      public People parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new People(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<People> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<People> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.backpocket.data.Data.People getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:main.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string FirstName = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string FirstName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string LastName = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string LastName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string Email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string Email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string City = 4;</code>
     */
    java.lang.String getCity();
    /**
     * <code>string City = 4;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string Country = 5;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>string Country = 5;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>int32 Age = 6;</code>
     */
    int getAge();

    /**
     * <code>int32 omittedInt = 7;</code>
     */
    int getOmittedInt();

    /**
     * <code>string omittedString = 8;</code>
     */
    java.lang.String getOmittedString();
    /**
     * <code>string omittedString = 8;</code>
     */
    com.google.protobuf.ByteString
        getOmittedStringBytes();

    /**
     * <code>string excluded = 9;</code>
     */
    java.lang.String getExcluded();
    /**
     * <code>string excluded = 9;</code>
     */
    com.google.protobuf.ByteString
        getExcludedBytes();

    /**
     * <code>string private = 10;</code>
     */
    java.lang.String getPrivate();
    /**
     * <code>string private = 10;</code>
     */
    com.google.protobuf.ByteString
        getPrivateBytes();
  }
  /**
   * Protobuf type {@code main.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:main.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      city_ = "";
      country_ = "";
      age_ = 0;
      omittedInt_ = 0;
      omittedString_ = "";
      excluded_ = "";
      private_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 48: {

              age_ = input.readInt32();
              break;
            }
            case 56: {

              omittedInt_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              omittedString_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              excluded_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              private_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.backpocket.data.Data.internal_static_main_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.backpocket.data.Data.internal_static_main_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.backpocket.data.Data.Person.class, com.backpocket.data.Data.Person.Builder.class);
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string FirstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string FirstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string LastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string LastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string Email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string Email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 4;
    private volatile java.lang.Object city_;
    /**
     * <code>string City = 4;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string City = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 5;
    private volatile java.lang.Object country_;
    /**
     * <code>string Country = 5;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string Country = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 6;
    private int age_;
    /**
     * <code>int32 Age = 6;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int OMITTEDINT_FIELD_NUMBER = 7;
    private int omittedInt_;
    /**
     * <code>int32 omittedInt = 7;</code>
     */
    public int getOmittedInt() {
      return omittedInt_;
    }

    public static final int OMITTEDSTRING_FIELD_NUMBER = 8;
    private volatile java.lang.Object omittedString_;
    /**
     * <code>string omittedString = 8;</code>
     */
    public java.lang.String getOmittedString() {
      java.lang.Object ref = omittedString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        omittedString_ = s;
        return s;
      }
    }
    /**
     * <code>string omittedString = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOmittedStringBytes() {
      java.lang.Object ref = omittedString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        omittedString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCLUDED_FIELD_NUMBER = 9;
    private volatile java.lang.Object excluded_;
    /**
     * <code>string excluded = 9;</code>
     */
    public java.lang.String getExcluded() {
      java.lang.Object ref = excluded_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excluded_ = s;
        return s;
      }
    }
    /**
     * <code>string excluded = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExcludedBytes() {
      java.lang.Object ref = excluded_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excluded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIVATE_FIELD_NUMBER = 10;
    private volatile java.lang.Object private_;
    /**
     * <code>string private = 10;</code>
     */
    public java.lang.String getPrivate() {
      java.lang.Object ref = private_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        private_ = s;
        return s;
      }
    }
    /**
     * <code>string private = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPrivateBytes() {
      java.lang.Object ref = private_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        private_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, country_);
      }
      if (age_ != 0) {
        output.writeInt32(6, age_);
      }
      if (omittedInt_ != 0) {
        output.writeInt32(7, omittedInt_);
      }
      if (!getOmittedStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, omittedString_);
      }
      if (!getExcludedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, excluded_);
      }
      if (!getPrivateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, private_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, country_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, age_);
      }
      if (omittedInt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, omittedInt_);
      }
      if (!getOmittedStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, omittedString_);
      }
      if (!getExcludedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, excluded_);
      }
      if (!getPrivateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, private_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.backpocket.data.Data.Person)) {
        return super.equals(obj);
      }
      com.backpocket.data.Data.Person other = (com.backpocket.data.Data.Person) obj;

      boolean result = true;
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getCity()
          .equals(other.getCity());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && (getAge()
          == other.getAge());
      result = result && (getOmittedInt()
          == other.getOmittedInt());
      result = result && getOmittedString()
          .equals(other.getOmittedString());
      result = result && getExcluded()
          .equals(other.getExcluded());
      result = result && getPrivate()
          .equals(other.getPrivate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + OMITTEDINT_FIELD_NUMBER;
      hash = (53 * hash) + getOmittedInt();
      hash = (37 * hash) + OMITTEDSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getOmittedString().hashCode();
      hash = (37 * hash) + EXCLUDED_FIELD_NUMBER;
      hash = (53 * hash) + getExcluded().hashCode();
      hash = (37 * hash) + PRIVATE_FIELD_NUMBER;
      hash = (53 * hash) + getPrivate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.backpocket.data.Data.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.backpocket.data.Data.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.backpocket.data.Data.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.backpocket.data.Data.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.backpocket.data.Data.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.backpocket.data.Data.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.backpocket.data.Data.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code main.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:main.Person)
        com.backpocket.data.Data.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.backpocket.data.Data.internal_static_main_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.backpocket.data.Data.internal_static_main_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.backpocket.data.Data.Person.class, com.backpocket.data.Data.Person.Builder.class);
      }

      // Construct using com.backpocket.data.Data.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        email_ = "";

        city_ = "";

        country_ = "";

        age_ = 0;

        omittedInt_ = 0;

        omittedString_ = "";

        excluded_ = "";

        private_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.backpocket.data.Data.internal_static_main_Person_descriptor;
      }

      @java.lang.Override
      public com.backpocket.data.Data.Person getDefaultInstanceForType() {
        return com.backpocket.data.Data.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.backpocket.data.Data.Person build() {
        com.backpocket.data.Data.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.backpocket.data.Data.Person buildPartial() {
        com.backpocket.data.Data.Person result = new com.backpocket.data.Data.Person(this);
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.email_ = email_;
        result.city_ = city_;
        result.country_ = country_;
        result.age_ = age_;
        result.omittedInt_ = omittedInt_;
        result.omittedString_ = omittedString_;
        result.excluded_ = excluded_;
        result.private_ = private_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.backpocket.data.Data.Person) {
          return mergeFrom((com.backpocket.data.Data.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.backpocket.data.Data.Person other) {
        if (other == com.backpocket.data.Data.Person.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getOmittedInt() != 0) {
          setOmittedInt(other.getOmittedInt());
        }
        if (!other.getOmittedString().isEmpty()) {
          omittedString_ = other.omittedString_;
          onChanged();
        }
        if (!other.getExcluded().isEmpty()) {
          excluded_ = other.excluded_;
          onChanged();
        }
        if (!other.getPrivate().isEmpty()) {
          private_ = other.private_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.backpocket.data.Data.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.backpocket.data.Data.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string FirstName = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FirstName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FirstName = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FirstName = 1;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string FirstName = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string LastName = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string LastName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string LastName = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string LastName = 2;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string LastName = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string Email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string Email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string City = 4;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string City = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string City = 4;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string City = 4;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string City = 4;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string Country = 5;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Country = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Country = 5;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Country = 5;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string Country = 5;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 Age = 6;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 Age = 6;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Age = 6;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int omittedInt_ ;
      /**
       * <code>int32 omittedInt = 7;</code>
       */
      public int getOmittedInt() {
        return omittedInt_;
      }
      /**
       * <code>int32 omittedInt = 7;</code>
       */
      public Builder setOmittedInt(int value) {
        
        omittedInt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 omittedInt = 7;</code>
       */
      public Builder clearOmittedInt() {
        
        omittedInt_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object omittedString_ = "";
      /**
       * <code>string omittedString = 8;</code>
       */
      public java.lang.String getOmittedString() {
        java.lang.Object ref = omittedString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          omittedString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string omittedString = 8;</code>
       */
      public com.google.protobuf.ByteString
          getOmittedStringBytes() {
        java.lang.Object ref = omittedString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          omittedString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string omittedString = 8;</code>
       */
      public Builder setOmittedString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        omittedString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string omittedString = 8;</code>
       */
      public Builder clearOmittedString() {
        
        omittedString_ = getDefaultInstance().getOmittedString();
        onChanged();
        return this;
      }
      /**
       * <code>string omittedString = 8;</code>
       */
      public Builder setOmittedStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        omittedString_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object excluded_ = "";
      /**
       * <code>string excluded = 9;</code>
       */
      public java.lang.String getExcluded() {
        java.lang.Object ref = excluded_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          excluded_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string excluded = 9;</code>
       */
      public com.google.protobuf.ByteString
          getExcludedBytes() {
        java.lang.Object ref = excluded_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          excluded_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string excluded = 9;</code>
       */
      public Builder setExcluded(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        excluded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string excluded = 9;</code>
       */
      public Builder clearExcluded() {
        
        excluded_ = getDefaultInstance().getExcluded();
        onChanged();
        return this;
      }
      /**
       * <code>string excluded = 9;</code>
       */
      public Builder setExcludedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        excluded_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object private_ = "";
      /**
       * <code>string private = 10;</code>
       */
      public java.lang.String getPrivate() {
        java.lang.Object ref = private_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          private_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string private = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPrivateBytes() {
        java.lang.Object ref = private_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          private_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string private = 10;</code>
       */
      public Builder setPrivate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        private_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string private = 10;</code>
       */
      public Builder clearPrivate() {
        
        private_ = getDefaultInstance().getPrivate();
        onChanged();
        return this;
      }
      /**
       * <code>string private = 10;</code>
       */
      public Builder setPrivateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        private_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:main.Person)
    }

    // @@protoc_insertion_point(class_scope:main.Person)
    private static final com.backpocket.data.Data.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.backpocket.data.Data.Person();
    }

    public static com.backpocket.data.Data.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.backpocket.data.Data.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_People_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_People_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\004main\"\'\n\006People\022\035\n\007Members\030" +
      "\001 \003(\0132\014.main.Person\"\266\001\n\006Person\022\021\n\tFirstN" +
      "ame\030\001 \001(\t\022\020\n\010LastName\030\002 \001(\t\022\r\n\005Email\030\003 \001" +
      "(\t\022\014\n\004City\030\004 \001(\t\022\017\n\007Country\030\005 \001(\t\022\013\n\003Age" +
      "\030\006 \001(\005\022\022\n\nomittedInt\030\007 \001(\005\022\025\n\romittedStr" +
      "ing\030\010 \001(\t\022\020\n\010excluded\030\t \001(\t\022\017\n\007private\030\n" +
      " \001(\tB\025\n\023com.backpocket.datab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_main_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_main_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_People_descriptor,
        new java.lang.String[] { "Members", });
    internal_static_main_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_main_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_Person_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "City", "Country", "Age", "OmittedInt", "OmittedString", "Excluded", "Private", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
